import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  Document,
  HlcClock,
  compareStamp,
  decodeSnapshot,
  encodeSnapshot,
  fracindex,
  hashHex,
  hex,
  idToJson,
  opFromJson,
  type OpJson,
} from "../src/index.js";

const FIXTURES = join(import.meta.dirname, "../../../../fixtures");

interface EngineFixture {
  name: string;
  ops: OpJson[];
  expected_hash: string;
  expected_snapshot: string;
  render_order: Array<{ replica: string; counter: string }>;
}

function mulberry(seed: number) {
  return () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

describe("engine fixtures (generated by converge-core)", () => {
  const dir = join(FIXTURES, "engine");
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort();
  expect(files.length).toBeGreaterThan(10);

  for (const file of files) {
    const fx = JSON.parse(readFileSync(join(dir, file), "utf8")) as EngineFixture;
    it(`${fx.name}: hash, snapshot, render order`, () => {
      const ops = fx.ops.map(opFromJson);
      const doc = new Document();
      for (const op of ops) doc.apply(op);
      expect(hashHex(doc)).toBe(fx.expected_hash);
      expect(hex(encodeSnapshot(doc))).toBe(fx.expected_snapshot);
      expect(doc.renderOrder().map(([id]) => idToJson(id))).toEqual(fx.render_order);

      const decoded = decodeSnapshot(encodeSnapshot(doc));
      expect(hashHex(decoded)).toBe(fx.expected_hash);

      // Reapplying is a no-op.
      for (const op of ops) expect(doc.apply(op)).toBe(false);
      expect(hashHex(doc)).toBe(fx.expected_hash);
    });

    it(`${fx.name}: converges under shuffles and duplicates`, () => {
      const ops = fx.ops.map(opFromJson);
      const rnd = mulberry(ops.length + 17);
      for (let round = 0; round < 3; round++) {
        const perm = [...ops, ...ops.filter(() => rnd() < 0.3)];
        for (let i = perm.length - 1; i > 0; i--) {
          const j = Math.floor(rnd() * (i + 1));
          [perm[i], perm[j]] = [perm[j]!, perm[i]!];
        }
        const doc = new Document();
        for (const op of perm) doc.apply(op);
        expect(hashHex(doc)).toBe(fx.expected_hash);
      }
    });
  }
});

describe("fractional index fixtures", () => {
  const fx = JSON.parse(readFileSync(join(FIXTURES, "fracindex.json"), "utf8")) as {
    cases: Array<{ a: string | null; b: string | null; expected: string }>;
    errors: Array<{ a: string | null; b: string | null }>;
  };
  it("matches every reference case", () => {
    for (const c of fx.cases)
      expect(fracindex.between(c.a, c.b), `between(${c.a}, ${c.b})`).toBe(c.expected);
  });
  it("rejects the error cases", () => {
    for (const c of fx.errors) expect(() => fracindex.between(c.a, c.b)).toThrow();
  });
});

describe("hlc fixtures", () => {
  const fx = JSON.parse(readFileSync(join(FIXTURES, "hlc.json"), "utf8")) as {
    stamp_pairs: Array<{
      a: { wall: string; logical: number; replica: string };
      b: { wall: string; logical: number; replica: string };
      cmp: number;
    }>;
    clock_trace: Array<{
      physical: string;
      observe: { wall: string; logical: number } | null;
      tick: { wall: string; logical: number };
    }>;
  };
  it("orders stamps identically (full u64 replica compare)", () => {
    for (const p of fx.stamp_pairs) {
      const a = {
        hlc: { wall: BigInt(p.a.wall), logical: p.a.logical },
        replica: BigInt(p.a.replica),
      };
      const b = {
        hlc: { wall: BigInt(p.b.wall), logical: p.b.logical },
        replica: BigInt(p.b.replica),
      };
      expect(Math.sign(compareStamp(a, b))).toBe(p.cmp);
    }
  });
  it("replays the clock trace", () => {
    const clock = new HlcClock();
    for (const step of fx.clock_trace) {
      if (step.observe)
        clock.observe(
          { wall: BigInt(step.observe.wall), logical: step.observe.logical },
          BigInt(step.physical),
        );
      const t = clock.tick(BigInt(step.physical));
      expect(t).toEqual({ wall: BigInt(step.tick.wall), logical: step.tick.logical });
    }
  });
});
